* Title: We should all be luddites
** Thesis: Luddites weren't AFRAID of new technology, they were MINDFUL of it, and recognized its potential harm to society.

** Everyone thinks the luddites were afraid of new technology, so burned down the looms.
A whole bunch of irrational actors afraid of the unknown.

*** Common knowledge (wikipedia):
#+BEGIN_QUOTE
The Luddites were members of a 19th-century movement of English textile workers who opposed the use of certain types of automated machinery due to concerns relating to worker pay and output quality. They often destroyed the machines in organised raids.[1][2] Members of the group referred to themselves as Luddites, self-described followers of "Ned Ludd", a legendary weaver whose name was used as a pseudonym in threatening letters to mill owners and government officials.
#+END_QUOTE
Luddites were subject to execution and penal transportation

#+BEGIN_QUOTE
The name Luddite (/ˈlʌdaɪt/) occurs in the movement's writings as early as 1811.[3] The movement utilised the eponym of Ned Ludd, an apocryphal apprentice who allegedly smashed two stocking frames in 1779 after being criticised and instructed to change his method. The name often appears as Captain, General, or King Ludd. Different versions of the legends place his residence in Anstey, near Leicester, or Sherwood Forest like Robin Hood.
#+END_QUOTE

#+BEGIN_QUOTE
In Lancashire, new cotton spinning technologies were met with violent resistance in 1768 and 1779. These new inventions produced textiles faster and cheaper because they could be operated by less-skilled, low-wage labourers.[11] These struggles sometimes resulted in government suppression, via Parliamentary acts such as the Protection of Stocking Frames, etc. Act 1788.
#+END_QUOTE

#+BEGIN_QUOTE
Malcolm L. Thomas argued in his 1970 history The Luddites that machine-breaking was one of the very few tactics that workers could use to increase pressure on employers, undermine lower-paid competing workers, and create solidarity among workers. "These attacks on machines did not imply any necessary hostility to machinery as such; machinery was just a conveniently exposed target against which an attack could be made."[10] Historian Eric Hobsbawm has called their machine wrecking "collective bargaining by riot", which had been a tactic used in Britain since the Restoration because manufactories were scattered throughout the country, and that made it impractical to hold large-scale strikes.
#+END_QUOTE

** The luddites were 'afraid' of automation, not of technology.
*** They're fear wasn't of the unknown, which is how a lot of people like to make it out, but the fear of automation's effect on production quality and jobs.
** Maybe the luddites were right, and maybe it applies to current times too.
*** AI is already making music and movies and stuff
**** An AI generated band on spotify is rising the charts.
https://www.bbc.com/news/articles/cp8mjnn7eqno
(I'm not sure this isn't just some kind of art project but we'll see.)
**** AI Fake news
***** John Oliver story about AI Slop
https://youtu.be/TWpg1RmzAbc?si=57JAI9OqNKkuRyLU

***** VT article about AI fake news
https://news.vt.edu/articles/2024/02/AI-generated-fake-news-experts.html

***** MIT article
https://www.technologyreview.com/2023/10/04/1080801/generative-ai-boosting-disinformation-and-propaganda-freedom-house/
Governments and politicians are using it for propaganda

***** DISA article
https://disa.org/the-impact-of-fake-news-statistics-by-country-artificial-intelligence-influence-and-misinformation-trends/
****** DISA is interesting because the website is super vague. It seems to (parade as?) some type of industry group for social media companies to work together to combat misinformation or something, but the website is only a bunch of blog posts. No 'about' section, no contact information, copyright info is only 'DISA'
**** Problem with AI generated content is that LLMs aren't capable of creativity
A lot of people would probably argue with that, I should read up more on that
***** When you look at an AI generated image closely, you can just /tell/ that it is fake.
****** Uncanny valley
***** AI also used to create fake news for propaganda.
****** If more people just paid more attention instead of scrolling and clicking, it probably wouldn't be as bad.
****** 
*** Companies haven't cared about quality for a long time. Products are designed to keep our attention, not make us more productive.
*** In the last couple of years, companies have OPENLY ADMITTED to trying to automate away jobs.

** We should be more mindful with how we use our devices
*** The device we (anecdotally) interact with the most is our phones, but they are black boxes. No one has any idea what happens behind the screen.
https://explodingtopics.com/blog/smartphone-usage-stats ?
https://www.npr.org/2021/08/13/1027317245/how-much-phone-time-is-too-much-phone-time-scientists-research-digital-addiction

- https://www.harmonyhit.com/phone-screen-time-statistics/
  Americans spend 5 hours and 16 minutes per day on average on their phones.

  "Phones are so much more than communication devices. They can operate as everything from payment systems to health data trackers to keys, levels, tuners, and even light switches. On top of these useful abilities, these devices can quickly become a time suck, drawing people in with social media, games, and streaming services."
  We come for the useful stuff, but then we get addicted.

  Recommend spending no longer than two hours a day on screens
  https://www.nhlbi.nih.gov/health/educational/wecan/reduce-screen-time/index.htm

  From harmony healthcare it: apparently 66% of gen z want to spend less time on their phones? If I'm reading the infographic correctly. 53% overall. Also, 69% of gen z are addicted to their phones, 49% overall

  72% of gen z think their mental health would improfe if apps were less addictive
  69% of gen z believe their social life would improve with less phone time.

  https://www.consumeraffairs.com/cell_phones/cell-phone-statistics.html
  https://www.addictionhelp.com/phone-addiction/statistics/

  harmonyhit addiction figures are self reported. Addictionhelp shows significantly lower numbers but I don't know the methodology.

  https://www.pewresearch.org/internet/fact-sheet/mobile/
  addiction help's numbers are similar to pew's numbers
*** People are too eager to sign up for any and everything, without asking any questions at all. Would you be that careless with your phone number? home address? social security number?
*** We need to stop trusting our data and our attention to companies operating in bad faith
*** As many people as possible need to understand that the app isn't the product, the user is.
** We need to prioritize tech and media literacy.
** We also need to prioritize tech mindfulness
Mental health
Stop Doom Scolling

** Tell 'em whatcha told 'em

** Random Thoughts

*** What other black boxes were there before broadband and smartphones? Before personal computers?
The black box argument maybe isn't great. I guess there are and always have been a lot of things people use without knowing how they work. The bigger issue is the attention/data harvesting

Black Box was coined around 1945 per wikipedia, so I guess it really has mostly been used in terms of computing.
Wilhelm Cauer didn't use the term, but is credited with the idea.
Ross Ashby and Norbert Wiener fleshed out the idea.

I'm maybe getting too in the weeds about this. The point is you use your phone despite having no idea how any of it works, and unlike older 'black boxes' like a washing machine, it's notoriously difficult to figure out how it works, hardware wise at least.

*** Social media companies are (verifiably?) deliberately dividing us, scaring us so we'll give them more attention.
*** Google lets you store your documents, photos, and emails on their servers for free, because they're sucking as much data and personal information as they can out of all that stuff. And they're selling all that information to anyone who has enough money, including governments.
*** Google carelessly deletes users' data to cover their own asses.
**** Guy who sent photos of his kid to the pediatrician, and google banned him for child porn. He appealed multiple times and never regained access. he lost lots of important documents because he was only storing them in google.

*** Phones/social media/mobile games are designed to be as addictive as possible. If anyone were addicted to alcohol, tobacco, or drugs the way they were addicted to their phone, their friends and family would have massive concerns.
**** Social media companies using the same tactics as big tobacco in the 90s

*** Social media widely known to be used for surveilance.
