* Title: We should all be luddites
** Thesis: Luddites weren't AFRAID of new technology, they were MINDFUL of it, and recognized its potential harm to society.

** The device we (anecdotally) interact with the most is our phones, but they are black boxes. No one has any idea what happens behind the screen.
https://explodingtopics.com/blog/smartphone-usage-stats ?
https://www.npr.org/2021/08/13/1027317245/how-much-phone-time-is-too-much-phone-time-scientists-research-digital-addiction

- https://www.harmonyhit.com/phone-screen-time-statistics/
  Americans spend 5 hours and 16 minutes per day on average on their phones.

  "Phones are so much more than communication devices. They can operate as everything from payment systems to health data trackers to keys, levels, tuners, and even light switches. On top of these useful abilities, these devices can quickly become a time suck, drawing people in with social media, games, and streaming services."
  We come for the useful stuff, but then we get addicted.

  Recommend spending no longer than two hours a day on screens
  https://www.nhlbi.nih.gov/health/educational/wecan/reduce-screen-time/index.htm

  From harmony healthcare it: apparently 66% of gen z want to spend less time on their phones? If I'm reading the infographic correctly. 53% overall. Also, 69% of gen z are addicted to their phones, 49% overall

  72% of gen z think their mental health would improfe if apps were less addictive
  69% of gen z believe their social life would improve with less phone time.

  https://www.consumeraffairs.com/cell_phones/cell-phone-statistics.html
  https://www.addictionhelp.com/phone-addiction/statistics/

  harmonyhit addiction figures are self reported. Addictionhelp shows significantly lower numbers but I don't know the methodology.

  https://www.pewresearch.org/internet/fact-sheet/mobile/
  addiction help's numbers are similar to pew's numbers

** What other black boxes were there before broadband and smartphones? Before personal computers?
The black box argument maybe isn't great. I guess there are and always have been a lot of things people use without knowing how they work. The bigger issue is the attention/data harvesting

** People are too eager to sign up for any and everything, without asking any questions at all. Would you be that careless with your phone number? home address? social security number?

** The luddites were 'afraid' of automation, not of technology. They're fear wasn't of the unknown, which is how a lot of people like to make it out, but the fear of automation's effect on production quality and jobs.
*** Companies haven't cared about quality for a long time. Products are designed to keep our attention, not make us more productive.
*** In the last couple of years, companies have OPENLY ADMITTED to trying to automate away jobs.

** As many people as possible need to understand that the app isn't the product, the user is.

** We need to stop trusting our data and our attention to companies operating in bad faith
*** Social media companies are (verifiably?) deliberately dividing us, scaring us so we'll give them more attention.
*** Google lets you store your documents, photos, and emails on their servers for free, because they're sucking as much data and personal information as they can out of all that stuff. And they're selling all that information to anyone who has enough money, including governments.
*** Google carelessly deletes users' data to cover their own asses.
**** Guy who sent photos of his kid to the pediatrician, and google banned him for child porn. He appealed multiple times and never regained access. he lost lots of important documents because he was only storing them in google.

** Phones/social media/mobile games are designed to be as addictive as possible. If anyone were addicted to alcohol, tobacco, or drugs the way they were addicted to their phone, their friends and family would have massive concerns.
*** Social media companies using the same tactics as big tobacco in the 90s

** Social media widely known to be used for surveilance.
